### ISSUE TITLE
Document how to create Jupyter notebooks with release candidates in README

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-examples#31]
[This PR](https://github.com/delta-io/delta-examples/pull/28) shows how to create a Jupyter notebook with a release candidate.

Let's document this in the README because it's a cool design pattern for folks that want to try out the release candidates.

**Comment by nkarpov** [comment]
👍 closed by https://github.com/delta-io/delta-examples/commit/535a05cd4c2bf240ef927df14d81da489df98a83
